-- VHDL Entity CPU_Design_lib.ALU_TopLevel.symbol
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS17)
--          at - 15:22:15 12/ 8/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY ALU_TopLevel IS
   PORT( 
      A          : IN     std_logic_vector (8 DOWNTO 0);
      B          : IN     std_logic_vector (8 DOWNTO 0);
      selection  : IN     std_logic_vector (2 DOWNTO 0);
      ALU_MuxOut : OUT    std_logic_vector (8 DOWNTO 0)
   );

-- Declarations

END ALU_TopLevel ;

--
-- VHDL Architecture CPU_Design_lib.ALU_TopLevel.struct
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS17)
--          at - 15:22:14 12/ 8/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY CPU_Design_lib;

ARCHITECTURE struct OF ALU_TopLevel IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL addMux    : std_logic_vector(8 DOWNTO 0);
   SIGNAL data_out  : std_logic_vector(8 DOWNTO 0);
   SIGNAL data_out1 : std_logic_vector(8 DOWNTO 0);
   SIGNAL data_out2 : std_logic_vector(8 DOWNTO 0);
   SIGNAL data_out3 : std_logic_vector(8 DOWNTO 0);
   SIGNAL data_out4 : std_logic_vector(8 DOWNTO 0);


   -- Component Declarations
   COMPONENT ALU_9bitAdder
   PORT (
      Cin      : IN     std_logic;
      data_in1 : IN     std_logic_vector (8 DOWNTO 0);
      data_in2 : IN     std_logic_vector (8 DOWNTO 0);
      data_out : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT ALU_And
   PORT (
      data_in1 : IN     std_logic_vector (8 DOWNTO 0);
      data_in2 : IN     std_logic_vector (8 DOWNTO 0);
      data_out : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT ALU_Inversion
   PORT (
      data_in  : IN     std_logic_vector (8 DOWNTO 0);
      data_out : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT ALU_Or
   PORT (
      data_in1 : IN     std_logic_vector (8 DOWNTO 0);
      data_in2 : IN     std_logic_vector (8 DOWNTO 0);
      data_out : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT MUX2to1x9bits
   PORT (
      A       : IN     std_logic_vector (8 DOWNTO 0);
      B       : IN     std_logic_vector (8 DOWNTO 0);
      sel     : IN     std_logic;
      MUX_OUT : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT MUX4to1x9bits
   PORT (
      A       : IN     std_logic_vector (8 DOWNTO 0);
      B       : IN     std_logic_vector (8 DOWNTO 0);
      C       : IN     std_logic_vector (8 DOWNTO 0);
      D       : IN     std_logic_vector (8 DOWNTO 0);
      sel     : IN     std_logic_vector (1 DOWNTO 0);
      MUX_OUT : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ALU_9bitAdder USE ENTITY CPU_Design_lib.ALU_9bitAdder;
   FOR ALL : ALU_And USE ENTITY CPU_Design_lib.ALU_And;
   FOR ALL : ALU_Inversion USE ENTITY CPU_Design_lib.ALU_Inversion;
   FOR ALL : ALU_Or USE ENTITY CPU_Design_lib.ALU_Or;
   FOR ALL : MUX2to1x9bits USE ENTITY CPU_Design_lib.MUX2to1x9bits;
   FOR ALL : MUX4to1x9bits USE ENTITY CPU_Design_lib.MUX4to1x9bits;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : ALU_9bitAdder
      PORT MAP (
         data_in1 => A,
         data_in2 => addMux,
         Cin      => selection(2),
         data_out => data_out1
      );
   U_1 : ALU_And
      PORT MAP (
         data_in1 => A,
         data_in2 => B,
         data_out => data_out2
      );
   U_3 : ALU_Inversion
      PORT MAP (
         data_in  => A,
         data_out => data_out4
      );
   U_4 : ALU_Inversion
      PORT MAP (
         data_in  => B,
         data_out => data_out
      );
   U_2 : ALU_Or
      PORT MAP (
         data_in1 => A,
         data_in2 => B,
         data_out => data_out3
      );
   U_6 : MUX2to1x9bits
      PORT MAP (
         A       => B,
         B       => data_out,
         sel     => selection(2),
         MUX_OUT => addMux
      );
   U_5 : MUX4to1x9bits
      PORT MAP (
         A       => data_out1,
         B       => data_out2,
         C       => data_out3,
         D       => data_out4,
         sel     => selection(1 DOWNTO 0),
         MUX_OUT => ALU_MuxOut
      );

END struct;
