-- VHDL Entity CPU_Design_lib.CPU_Top.symbol
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS17)
--          at - 15:25:10 12/ 8/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY CPU_Top IS
   PORT( 
      Data_In : IN     std_logic_vector (8 DOWNTO 0);
      Run     : IN     std_logic;
      clockIn : IN     std_logic;
      resetIn : IN     std_logic;
      CPU_Bus : OUT    std_logic_vector (8 DOWNTO 0);
      Done    : OUT    std_logic
   );

-- Declarations

END CPU_Top ;

--
-- VHDL Architecture CPU_Design_lib.CPU_Top.struct
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS17)
--          at - 15:25:10 12/ 8/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY CPU_Design_lib;

ARCHITECTURE struct OF CPU_Top IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clockOut : std_logic;
   SIGNAL resetOut : std_logic;


   -- Component Declarations
   COMPONENT FSM_Datapath
   PORT (
      Data_In : IN     std_logic_vector (8 DOWNTO 0);
      Run     : IN     std_logic ;
      clk     : IN     std_logic ;
      rst     : IN     std_logic ;
      CPU_Bus : OUT    std_logic_vector (8 DOWNTO 0);
      Done    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Invert
   PORT (
      clockIn  : IN     std_logic;
      resetIn  : IN     std_logic;
      clockOut : OUT    std_logic;
      resetOut : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FSM_Datapath USE ENTITY CPU_Design_lib.FSM_Datapath;
   FOR ALL : Invert USE ENTITY CPU_Design_lib.Invert;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : FSM_Datapath
      PORT MAP (
         Data_In => Data_In,
         Run     => Run,
         clk     => clockOut,
         rst     => resetOut,
         CPU_Bus => CPU_Bus,
         Done    => Done
      );
   U_1 : Invert
      PORT MAP (
         clockIn  => clockIn,
         resetIn  => resetIn,
         clockOut => clockOut,
         resetOut => resetOut
      );

END struct;
