-- VHDL Entity CPU_Design_lib.FSM_Datapath.symbol
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS17)
--          at - 15:09:19 12/ 8/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY FSM_Datapath IS
   PORT( 
      Data_In : IN     std_logic_vector (8 DOWNTO 0);
      Run     : IN     std_logic;
      clk     : IN     std_logic;
      rst     : IN     std_logic;
      CPU_Bus : OUT    std_logic_vector (8 DOWNTO 0);
      Done    : OUT    std_logic
   );

-- Declarations

END FSM_Datapath ;

--
-- VHDL Architecture CPU_Design_lib.FSM_Datapath.struct
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS17)
--          at - 15:26:35 12/ 8/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY CPU_Design_lib;

ARCHITECTURE struct OF FSM_Datapath IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL A             : std_logic_vector(8 DOWNTO 0);
   SIGNAL ALU_OUT       : std_logic_vector(8 DOWNTO 0);
   SIGNAL ALU_Op        : std_logic_vector(2 DOWNTO 0);
   SIGNAL A_en          : std_logic;
   SIGNAL Bus_Sel       : std_logic_vector(1 DOWNTO 0);
   SIGNAL C             : std_logic_vector(8 DOWNTO 0);
   SIGNAL F_en          : std_logic;
   SIGNAL IR_en         : std_logic;
   SIGNAL Read_Address  : std_logic_vector(2 DOWNTO 0);
   SIGNAL Write_Address : std_logic_vector(2 DOWNTO 0);
   SIGNAL Write_Enable  : std_logic;
   SIGNAL data_in1      : std_logic_vector(8 DOWNTO 0);
   SIGNAL data_out      : std_logic_vector(8 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL CPU_Bus_internal : std_logic_vector (8 DOWNTO 0);


   -- Component Declarations
   COMPONENT ALU_TopLevel
   PORT (
      A          : IN     std_logic_vector (8 DOWNTO 0);
      B          : IN     std_logic_vector (8 DOWNTO 0);
      selection  : IN     std_logic_vector (2 DOWNTO 0);
      ALU_MuxOut : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT FSM_Controller
   PORT (
      clk           : IN     std_logic ;
      data_in       : IN     std_logic_vector (8 DOWNTO 0);
      en            : IN     std_logic ;
      rst           : IN     std_logic ;
      ALU_Op        : OUT    std_logic_vector (2 DOWNTO 0);
      A_en          : OUT    std_logic ;
      Bus_Sel       : OUT    std_logic_vector (1 DOWNTO 0);
      F_en          : OUT    std_logic ;
      IR_en         : OUT    std_logic ;
      Read_Address  : OUT    std_logic_vector (2 DOWNTO 0);
      Write_Address : OUT    std_logic_vector (2 DOWNTO 0);
      Write_Enable  : OUT    std_logic ;
      done          : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT MUX3to1x9bits
   PORT (
      A       : IN     std_logic_vector (8 DOWNTO 0);
      B       : IN     std_logic_vector (8 DOWNTO 0);
      C       : IN     std_logic_vector (8 DOWNTO 0);
      sel     : IN     std_logic_vector (1 DOWNTO 0);
      MUX_OUT : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT REGISTER8x9bits
   PORT (
      Read_Address  : IN     std_logic_vector (2 DOWNTO 0);
      Write_Address : IN     std_logic_vector (2 DOWNTO 0);
      Write_Data    : IN     std_logic_vector (8 DOWNTO 0);
      clk           : IN     std_logic ;
      rst           : IN     std_logic ;
      write_enable  : IN     std_logic ;
      Read_Data     : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT registerStorage
   PORT (
      clk      : IN     std_logic;
      data_in  : IN     std_logic_vector (8 DOWNTO 0);
      en       : IN     std_logic;
      rst      : IN     std_logic;
      data_out : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ALU_TopLevel USE ENTITY CPU_Design_lib.ALU_TopLevel;
   FOR ALL : FSM_Controller USE ENTITY CPU_Design_lib.FSM_Controller;
   FOR ALL : MUX3to1x9bits USE ENTITY CPU_Design_lib.MUX3to1x9bits;
   FOR ALL : REGISTER8x9bits USE ENTITY CPU_Design_lib.REGISTER8x9bits;
   FOR ALL : registerStorage USE ENTITY CPU_Design_lib.registerStorage;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : ALU_TopLevel
      PORT MAP (
         A          => data_out,
         B          => CPU_Bus_internal,
         selection  => ALU_Op,
         ALU_MuxOut => ALU_OUT
      );
   Controller : FSM_Controller
      PORT MAP (
         clk           => clk,
         data_in       => data_in1,
         en            => Run,
         rst           => rst,
         ALU_Op        => ALU_Op,
         A_en          => A_en,
         Bus_Sel       => Bus_Sel,
         F_en          => F_en,
         IR_en         => IR_en,
         Read_Address  => Read_Address,
         Write_Address => Write_Address,
         Write_Enable  => Write_Enable,
         done          => Done
      );
   BUS_Mux : MUX3to1x9bits
      PORT MAP (
         A       => A,
         B       => Data_In,
         C       => C,
         sel     => Bus_Sel,
         MUX_OUT => CPU_Bus_internal
      );
   Register_File : REGISTER8x9bits
      PORT MAP (
         Read_Address  => Read_Address,
         Write_Address => Write_Address,
         Write_Data    => CPU_Bus_internal,
         clk           => clk,
         rst           => rst,
         write_enable  => Write_Enable,
         Read_Data     => C
      );
   F : registerStorage
      PORT MAP (
         data_in  => ALU_OUT,
         clk      => clk,
         rst      => rst,
         en       => F_en,
         data_out => A
      );
   IR : registerStorage
      PORT MAP (
         data_in  => Data_In,
         clk      => clk,
         rst      => rst,
         en       => IR_en,
         data_out => data_in1
      );
   RegA : registerStorage
      PORT MAP (
         data_in  => CPU_Bus_internal,
         clk      => clk,
         rst      => rst,
         en       => A_en,
         data_out => data_out
      );

   -- Implicit buffered output assignments
   CPU_Bus <= CPU_Bus_internal;

END struct;
