-- VHDL Entity CPU_Design_lib.Memory_Top.symbol
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS17)
--          at - 12:30:30 12/ 9/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Memory_Top IS
   PORT( 
      Run           : IN     std_logic;
      buttonM       : IN     STD_LOGIC;
      buttonP       : IN     STD_LOGIC;
      internalClock : IN     STD_LOGIC;
      reset         : IN     std_logic;
      CPU_Bus       : OUT    std_logic_vector (8 DOWNTO 0);
      Done          : OUT    std_logic
   );

-- Declarations

END Memory_Top ;

--
-- VHDL Architecture CPU_Design_lib.Memory_Top.struct
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS17)
--          at - 12:30:29 12/ 9/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY CPU_Design_lib;

ARCHITECTURE struct OF Memory_Top IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL MClock : std_logic;
   SIGNAL PClock : STD_LOGIC;
   SIGNAL count  : std_logic_vector(4 DOWNTO 0);
   SIGNAL q      : STD_LOGIC_VECTOR(8 DOWNTO 0);


   -- Component Declarations
   COMPONENT CPU_Top
   PORT (
      Data_In : IN     std_logic_vector (8 DOWNTO 0);
      Run     : IN     std_logic ;
      clockIn : IN     std_logic ;
      resetIn : IN     std_logic ;
      CPU_Bus : OUT    std_logic_vector (8 DOWNTO 0);
      Done    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT FiveBitCounter
   PORT (
      clock : IN     std_logic ;
      reset : IN     std_logic ;
      count : OUT    std_logic_vector (4 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT debounce
   GENERIC (
      clk_freq    : INTEGER := 50_000_000;      --system clock frequency in Hz
      stable_time : INTEGER := 10
   );
   PORT (
      button : IN     STD_LOGIC;
      clk    : IN     STD_LOGIC;
      result : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT inst_mem
   PORT (
      address : IN     STD_LOGIC_VECTOR (4 DOWNTO 0);
      clock   : IN     STD_LOGIC  := '1';
      q       : OUT    STD_LOGIC_VECTOR (8 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : CPU_Top USE ENTITY CPU_Design_lib.CPU_Top;
   FOR ALL : FiveBitCounter USE ENTITY CPU_Design_lib.FiveBitCounter;
   FOR ALL : debounce USE ENTITY CPU_Design_lib.debounce;
   FOR ALL : inst_mem USE ENTITY CPU_Design_lib.inst_mem;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : CPU_Top
      PORT MAP (
         Data_In => q,
         Run     => Run,
         clockIn => PClock,
         resetIn => reset,
         CPU_Bus => CPU_Bus,
         Done    => Done
      );
   U_2 : FiveBitCounter
      PORT MAP (
         reset => reset,
         clock => MClock,
         count => count
      );
   U_3 : debounce
      GENERIC MAP (
         clk_freq    => 50_000_000,         --system clock frequency in Hz
         stable_time => 10
      )
      PORT MAP (
         clk    => internalClock,
         button => buttonM,
         result => MClock
      );
   U_4 : debounce
      GENERIC MAP (
         clk_freq    => 50_000_000,         --system clock frequency in Hz
         stable_time => 10
      )
      PORT MAP (
         clk    => internalClock,
         button => buttonP,
         result => PClock
      );
   U_0 : inst_mem
      PORT MAP (
         address => count,
         clock   => MClock,
         q       => q
      );

END struct;
