-- VHDL Entity lmb_ECE0201_lib.Calculator.symbol
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS09)
--          at - 13:42:44 11/15/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Calculator IS
   PORT( 
      ALU_sel      : IN     std_logic_vector (1 DOWNTO 0);
      Data_In      : IN     std_logic_vector (7 DOWNTO 0);
      Read_Adress  : IN     std_logic_vector (1 DOWNTO 0);
      Write_Adress : IN     std_logic_vector (1 DOWNTO 0);
      clk          : IN     std_logic;
      data_sel     : IN     std_logic;
      en           : IN     std_logic;
      rst          : IN     std_logic;
      HEX0         : OUT    std_logic_vector (7 DOWNTO 0);
      HEX1         : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END Calculator ;

--
-- VHDL Architecture lmb_ECE0201_lib.Calculator.struct
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS09)
--          at - 13:45:47 11/15/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY lmb_ECE0201_lib;

ARCHITECTURE struct OF Calculator IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL MUX_OUT   : std_logic_vector(7 DOWNTO 0);
   SIGNAL OneHot    : std_logic_vector(1 DOWNTO 0);
   SIGNAL Read_Data : std_logic_vector(7 DOWNTO 0);
   SIGNAL Write     : std_logic_vector(7 DOWNTO 0);
   SIGNAL xOut      : std_logic_vector(7 DOWNTO 0);
   SIGNAL yOut      : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT ALU_TopLevel
   PORT (
      A       : IN     std_logic_vector (7 DOWNTO 0);
      B       : IN     std_logic_vector (7 DOWNTO 0);
      sel     : IN     std_logic_vector (1 DOWNTO 0);
      MUX_OUT : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT DisplayDecoder
   PORT (
      SW  : IN     std_logic_vector (3 DOWNTO 0);
      HEX : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT MUX2to1x8bits
   PORT (
      A            : IN     std_logic_vector (7 DOWNTO 0);
      B            : IN     std_logic_vector (7 DOWNTO 0);
      sel          : IN     std_logic;
      DATA_MUX_OUT : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT OneHotDecoder
   PORT (
      input  : IN     std_logic;
      output : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT REGFILE4x8
   PORT (
      Read_Adress  : IN     std_logic_vector (1 DOWNTO 0);
      Write_Adress : IN     std_logic_vector (1 DOWNTO 0);
      Write_Data   : IN     std_logic_vector (7 DOWNTO 0);
      clk          : IN     std_logic ;
      rst          : IN     std_logic ;
      Read_Data    : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT registerStorage
   PORT (
      clk      : IN     std_logic;
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      en       : IN     std_logic;
      rst      : IN     std_logic;
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ALU_TopLevel USE ENTITY lmb_ECE0201_lib.ALU_TopLevel;
   FOR ALL : DisplayDecoder USE ENTITY lmb_ECE0201_lib.DisplayDecoder;
   FOR ALL : MUX2to1x8bits USE ENTITY lmb_ECE0201_lib.MUX2to1x8bits;
   FOR ALL : OneHotDecoder USE ENTITY lmb_ECE0201_lib.OneHotDecoder;
   FOR ALL : REGFILE4x8 USE ENTITY lmb_ECE0201_lib.REGFILE4x8;
   FOR ALL : registerStorage USE ENTITY lmb_ECE0201_lib.registerStorage;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   ALU : ALU_TopLevel
      PORT MAP (
         A       => xOut,
         B       => yOut,
         sel     => ALU_sel,
         MUX_OUT => MUX_OUT
      );
   Display0 : DisplayDecoder
      PORT MAP (
         SW  => MUX_OUT(3 DOWNTO 0),
         HEX => HEX0
      );
   Display1 : DisplayDecoder
      PORT MAP (
         SW  => MUX_OUT(7 DOWNTO 4),
         HEX => HEX1
      );
   Data_Selector : MUX2to1x8bits
      PORT MAP (
         A            => Data_In,
         B            => MUX_OUT,
         sel          => data_sel,
         DATA_MUX_OUT => Write
      );
   U_0 : OneHotDecoder
      PORT MAP (
         input  => en,
         output => OneHot
      );
   ABCD_Reg : REGFILE4x8
      PORT MAP (
         Read_Adress  => Read_Adress,
         Write_Adress => Write_Adress,
         Write_Data   => Write,
         clk          => clk,
         rst          => rst,
         Read_Data    => Read_Data
      );
   X : registerStorage
      PORT MAP (
         data_in  => Read_Data,
         clk      => clk,
         rst      => rst,
         en       => OneHot(1),
         data_out => xOut
      );
   Y : registerStorage
      PORT MAP (
         data_in  => Read_Data,
         clk      => clk,
         rst      => rst,
         en       => OneHot(0),
         data_out => yOut
      );

END struct;
