-- VHDL Entity lmb_ECE0201_lib.CalcTopLevel.symbol
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-MEAS-EM11)
--          at - 17:31:51 11/17/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY CalcTopLevel IS
   PORT( 
      ALU_sel      : IN     std_logic_vector (1 DOWNTO 0);
      Read_Adress  : IN     std_logic_vector (1 DOWNTO 0);
      Write_Adress : IN     std_logic_vector (1 DOWNTO 0);
      clk          : IN     std_logic;
      data_sel     : IN     std_logic;
      en           : IN     std_logic;
      rst          : IN     std_logic;
      sel          : IN     std_logic;
      HEX0         : OUT    std_logic_vector (7 DOWNTO 0);
      HEX1         : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END CalcTopLevel ;

--
-- VHDL Architecture lmb_ECE0201_lib.CalcTopLevel.struct
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-MEAS-EM11)
--          at - 17:31:50 11/17/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY lmb_ECE0201_lib;

ARCHITECTURE struct OF CalcTopLevel IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL MUX_OUT : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout    : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1   : std_logic_vector(7 DOWNTO 0);
	signal notClk, notRst : std_logic;


   -- Component Declarations
   COMPONENT Calculator
   PORT (
      ALU_sel      : IN     std_logic_vector (1 DOWNTO 0);
      Data_In      : IN     std_logic_vector (7 DOWNTO 0);
      Read_Adress  : IN     std_logic_vector (1 DOWNTO 0);
      Write_Adress : IN     std_logic_vector (1 DOWNTO 0);
      clk          : IN     std_logic ;
      data_sel     : IN     std_logic ;
      en           : IN     std_logic ;
      rst          : IN     std_logic ;
      HEX0         : OUT    std_logic_vector (7 DOWNTO 0);
      HEX1         : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT MUX2to1x8bits
   PORT (
      A       : IN     std_logic_vector (7 DOWNTO 0);
      B       : IN     std_logic_vector (7 DOWNTO 0);
      sel     : IN     std_logic;
      MUX_OUT : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Calculator USE ENTITY lmb_ECE0201_lib.Calculator;
   FOR ALL : MUX2to1x8bits USE ENTITY lmb_ECE0201_lib.MUX2to1x8bits;
   -- pragma synthesis_on


BEGIN

	notClk <= not clk;
	notRst <= not rst;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   dout <= "01111000";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout1 <= "01000011";

   -- Instance port mappings.
   U_0 : Calculator
      PORT MAP (
         ALU_sel      => ALU_sel,
         Data_In      => MUX_OUT,
         Read_Adress  => Read_Adress,
         Write_Adress => Write_Adress,
         Clk          => notClk,
         data_sel     => data_sel,
         en           => en,
         Rst          => notRst,
         HEX0         => HEX0,
         HEX1         => HEX1
      );
   U_1 : MUX2to1x8bits
      PORT MAP (
         A       => dout,
         B       => dout1,
         sel     => sel,
         MUX_OUT => MUX_OUT
      );

END struct;
