-- VHDL Entity lmb_ECE0201_lib.REGFILE4x8.symbol
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS09)
--          at - 13:26:36 11/13/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY REGFILE4x8 IS
   PORT( 
      Read_Adress  : IN     std_logic_vector (1 DOWNTO 0);
      Write_Adress : IN     std_logic_vector (1 DOWNTO 0);
      Write_Data   : IN     std_logic_vector (7 DOWNTO 0);
      clk          : IN     std_logic;
      rst          : IN     std_logic;
      Read_Data    : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END REGFILE4x8 ;

--
-- VHDL Architecture lmb_ECE0201_lib.REGFILE4x8.struct
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS09)
--          at - 13:26:36 11/13/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY lmb_ECE0201_lib;

ARCHITECTURE struct OF REGFILE4x8 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL A      : std_logic_vector(7 DOWNTO 0);
   SIGNAL B      : std_logic_vector(7 DOWNTO 0);
   SIGNAL C      : std_logic_vector(7 DOWNTO 0);
   SIGNAL D      : std_logic_vector(7 DOWNTO 0);
   SIGNAL output : std_logic_vector(3 DOWNTO 0);


   -- Component Declarations
   COMPONENT DECODER2to4
   PORT (
      selection : IN     std_logic_vector (1 DOWNTO 0);
      output    : OUT    std_logic_vector (3 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT MUX4to1x8bits
   PORT (
      A       : IN     std_logic_vector (7 DOWNTO 0);
      B       : IN     std_logic_vector (7 DOWNTO 0);
      C       : IN     std_logic_vector (7 DOWNTO 0);
      D       : IN     std_logic_vector (7 DOWNTO 0);
      sel     : IN     std_logic_vector (1 DOWNTO 0);
      MUX_OUT : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT registerStorage
   PORT (
      clk      : IN     std_logic;
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      en       : IN     std_logic;
      rst      : IN     std_logic;
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DECODER2to4 USE ENTITY lmb_ECE0201_lib.DECODER2to4;
   FOR ALL : MUX4to1x8bits USE ENTITY lmb_ECE0201_lib.MUX4to1x8bits;
   FOR ALL : registerStorage USE ENTITY lmb_ECE0201_lib.registerStorage;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_5 : DECODER2to4
      PORT MAP (
         selection => Write_Adress,
         output    => output
      );
   U_0 : MUX4to1x8bits
      PORT MAP (
         A       => A,
         B       => B,
         C       => C,
         D       => D,
         sel     => Read_Adress,
         MUX_OUT => Read_Data
      );
   U_1 : registerStorage
      PORT MAP (
         data_in  => Write_Data,
         clk      => clk,
         rst      => rst,
         en       => output(0),
         data_out => A
      );
   U_2 : registerStorage
      PORT MAP (
         data_in  => Write_Data,
         clk      => clk,
         rst      => rst,
         en       => output(1),
         data_out => B
      );
   U_3 : registerStorage
      PORT MAP (
         data_in  => Write_Data,
         clk      => clk,
         rst      => rst,
         en       => output(2),
         data_out => C
      );
   U_4 : registerStorage
      PORT MAP (
         data_in  => Write_Data,
         clk      => clk,
         rst      => rst,
         en       => output(3),
         data_out => D
      );

END struct;
