-- VHDL Entity lmb_ECE0201_lib.TopLevelBlock.symbol
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS09)
--          at - 14:14:46 11/13/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY TopLevelBlock IS
   PORT( 
      Read_Adress  : IN     std_logic_vector (1 DOWNTO 0);
      Write_Adress : IN     std_logic_vector (1 DOWNTO 0);
      Write_Data   : IN     std_logic_vector (7 DOWNTO 0);
      clk          : IN     std_logic;
      rst          : IN     std_logic;
      HEX0         : OUT    std_logic_vector (7 DOWNTO 0);
      HEX1         : OUT    std_logic_vector (7 DOWNTO 0);
      HEX2         : OUT    std_logic_vector (7 DOWNTO 0);
      HEX3         : OUT    std_logic_vector (7 DOWNTO 0);
      Read_Data    : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END TopLevelBlock ;

--
-- VHDL Architecture lmb_ECE0201_lib.TopLevelBlock.struct
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS09)
--          at - 14:14:46 11/13/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY lmb_ECE0201_lib;

ARCHITECTURE struct OF TopLevelBlock IS

   -- Architecture declarations

   -- Internal signal declarations

   -- Implicit buffer signal declarations
   SIGNAL Read_Data_internal : std_logic_vector (7 DOWNTO 0);


   -- Component Declarations
   COMPONENT DisplayDecoder
   PORT (
      SW  : IN     std_logic_vector (3 DOWNTO 0);
      HEX : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT REGFILE4x8
   PORT (
      Read_Adress  : IN     std_logic_vector (1 DOWNTO 0);
      Write_Adress : IN     std_logic_vector (1 DOWNTO 0);
      Write_Data   : IN     std_logic_vector (7 DOWNTO 0);
      clk          : IN     std_logic ;
      rst          : IN     std_logic ;
      Read_Data    : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DisplayDecoder USE ENTITY lmb_ECE0201_lib.DisplayDecoder;
   FOR ALL : REGFILE4x8 USE ENTITY lmb_ECE0201_lib.REGFILE4x8;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : DisplayDecoder
      PORT MAP (
         SW  => Write_Data(7 DOWNTO 4),
         HEX => HEX1
      );
   U_2 : DisplayDecoder
      PORT MAP (
         SW  => Write_Data(3 DOWNTO 0),
         HEX => HEX0
      );
   U_3 : DisplayDecoder
      PORT MAP (
         SW  => Read_Data_internal(7 DOWNTO 4),
         HEX => HEX3
      );
   U_4 : DisplayDecoder
      PORT MAP (
         SW  => Read_Data_internal(3 DOWNTO 0),
         HEX => HEX2
      );
   U_0 : REGFILE4x8
      PORT MAP (
         Read_Adress  => Read_Adress,
         Write_Adress => Write_Adress,
         Write_Data   => Write_Data,
         clk          => clk,
         rst          => rst,
         Read_Data    => Read_Data_internal
      );

   -- Implicit buffered output assignments
   Read_Data <= Read_Data_internal;

END struct;
