-- VHDL Entity CPU_Design_lib.REGISTER8x9bits.symbol
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS19)
--          at - 13:00:57 11/20/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY REGISTER8x9bits IS
   PORT( 
      Read_Address  : IN     std_logic_vector (2 DOWNTO 0);
      Write_Address : IN     std_logic_vector (2 DOWNTO 0);
      Write_Data    : IN     std_logic_vector (8 DOWNTO 0);
      clk           : IN     std_logic;
      rst           : IN     std_logic;
      Read_Data     : OUT    std_logic_vector (8 DOWNTO 0)
   );

-- Declarations

END REGISTER8x9bits ;

--
-- VHDL Architecture CPU_Design_lib.REGISTER8x9bits.struct
--
-- Created:
--          by - lmb290.UNKNOWN (SSOE-COELABS19)
--          at - 13:00:57 11/20/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY CPU_Design_lib;

ARCHITECTURE struct OF REGISTER8x9bits IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL E         : std_logic_vector(8 DOWNTO 0);
   SIGNAL F         : std_logic_vector(8 DOWNTO 0);
   SIGNAL G         : std_logic_vector(8 DOWNTO 0);
   SIGNAL H         : std_logic_vector(8 DOWNTO 0);
   SIGNAL data_out  : std_logic_vector(8 DOWNTO 0);
   SIGNAL data_out1 : std_logic_vector(8 DOWNTO 0);
   SIGNAL data_out2 : std_logic_vector(8 DOWNTO 0);
   SIGNAL data_out3 : std_logic_vector(8 DOWNTO 0);
   SIGNAL output    : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT DECODER3to8
   PORT (
      selection : IN     std_logic_vector (2 DOWNTO 0);
      output    : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT MUX8to1x9bits
   PORT (
      A         : IN     std_logic_vector (8 DOWNTO 0);
      B         : IN     std_logic_vector (8 DOWNTO 0);
      C         : IN     std_logic_vector (8 DOWNTO 0);
      D         : IN     std_logic_vector (8 DOWNTO 0);
      E         : IN     std_logic_vector (8 DOWNTO 0);
      F         : IN     std_logic_vector (8 DOWNTO 0);
      G         : IN     std_logic_vector (8 DOWNTO 0);
      H         : IN     std_logic_vector (8 DOWNTO 0);
      selection : IN     std_logic_vector (2 DOWNTO 0);
      output    : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT registerStorage
   PORT (
      clk      : IN     std_logic;
      data_in  : IN     std_logic_vector (8 DOWNTO 0);
      en       : IN     std_logic;
      rst      : IN     std_logic;
      data_out : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DECODER3to8 USE ENTITY CPU_Design_lib.DECODER3to8;
   FOR ALL : MUX8to1x9bits USE ENTITY CPU_Design_lib.MUX8to1x9bits;
   FOR ALL : registerStorage USE ENTITY CPU_Design_lib.registerStorage;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_8 : DECODER3to8
      PORT MAP (
         selection => Write_Address,
         output    => output
      );
   U_9 : MUX8to1x9bits
      PORT MAP (
         A         => data_out,
         B         => data_out1,
         C         => data_out2,
         D         => data_out3,
         E         => E,
         F         => F,
         G         => G,
         H         => H,
         selection => Read_Address,
         output    => Read_Data
      );
   U_0 : registerStorage
      PORT MAP (
         data_in  => Write_Data,
         clk      => clk,
         rst      => rst,
         en       => output(0),
         data_out => data_out
      );
   U_1 : registerStorage
      PORT MAP (
         data_in  => Write_Data,
         clk      => clk,
         rst      => rst,
         en       => output(1),
         data_out => data_out1
      );
   U_2 : registerStorage
      PORT MAP (
         data_in  => Write_Data,
         clk      => clk,
         rst      => rst,
         en       => output(2),
         data_out => data_out2
      );
   U_3 : registerStorage
      PORT MAP (
         data_in  => Write_Data,
         clk      => clk,
         rst      => rst,
         en       => output(3),
         data_out => data_out3
      );
   U_4 : registerStorage
      PORT MAP (
         data_in  => Write_Data,
         clk      => clk,
         rst      => rst,
         en       => output(4),
         data_out => E
      );
   U_5 : registerStorage
      PORT MAP (
         data_in  => Write_Data,
         clk      => clk,
         rst      => rst,
         en       => output(5),
         data_out => F
      );
   U_6 : registerStorage
      PORT MAP (
         data_in  => Write_Data,
         clk      => clk,
         rst      => rst,
         en       => output(6),
         data_out => G
      );
   U_7 : registerStorage
      PORT MAP (
         data_in  => Write_Data,
         clk      => clk,
         rst      => rst,
         en       => output(7),
         data_out => H
      );

END struct;
